name: chrisk15
favicon: null
layout_spectrum: 0.5354798992630094
typography_spectrum: 0.6723442033398896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3070396559778601
  lightness: 0.06846358184702694
  saturation: 0.25470694131217897
  rhythmicContrast: 0.25455759302712977
purpose: []
